### ISSUE TITLE
App is crashing after clicking at My recipes

### ISSUE THREAD

**Issue by grousso** [matthiasclasen/gr#13]
george@ubuntu:~$ flatpak run org.gnome.Recipes 
** Message: Load recipe db: /app/share/recipes/recipes.db
** Message: Load chefs db: /app/share/recipes/chefs.db
** Message: Load picks db: /app/share/recipes/picks.db
** Message: Load recipe db: /home/george/.var/app/org.gnome.Recipes/data/recipes/recipes.db
** Message: Load favorites db: /home/george/.var/app/org.gnome.Recipes/data/recipes/favorites.db
** Message: No cooked db at: /home/george/.var/app/org.gnome.Recipes/data/recipes/cooked.db
** Message: No chefs db at: /home/george/.var/app/org.gnome.Recipes/data/recipes/authors.db
** Message: Load user id: /home/george/.var/app/org.gnome.Recipes/data/recipes/user
** Message: 28 recipes loaded
** Message: 9 chefs loaded

(recipes:2): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.

** (recipes:2): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-nexAL4het4: Connection refused

(recipes:2): Gtk-WARNING **: Failed to get the GNOME session proxy: The name org.gnome.SessionManager is not owned

(recipes:2): Gtk-WARNING **: Failed to get the Xfce session proxy: The name org.xfce.SessionManager is not owned

(recipes:2): Gtk-WARNING **: Failed to get an inhibit portal proxy: The name org.freedesktop.portal.Desktop is not owned
** Message: Load CSS from: resource:///org/gnome/Recipes/recipes.css
** Message: Load CSS from: resource:///org/gnome/Recipes/cuisine.css

(recipes:2): GLib-GObject-CRITICAL **: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

**Comment by matthiasclasen** [comment]
it would be very useful if you could get a stacktrace of this crash, I haven't seen this.

**Comment by grousso** [comment]
maybe this is that you want
[gdb-recipes.txt](https://github.com/matthiasclasen/gr/files/711717/gdb-recipes.txt)

**Comment by matthiasclasen** [comment]
sadly, not very useful without debug information.
if this is the flatpak, can you install org.gnome.Recipes.Debug from the same location, and then do

flatpak run --devel --runtime=org.gnome.Sdk --command=sh org.gnome.Recipes
gdb /app/bin/recipes

and then reproduce the crash ?
that should give a better stacktrace with debug symbols for the app

for even better results, make sure that org.gnome.Sdk.Debug is installed as well

**Comment by grousso** [comment]
Thanks for the guidelines
[recipes-debug.txt](https://github.com/matthiasclasen/gr/files/720498/recipes-debug.txt)

**Comment by matthiasclasen** [comment]
I believe I fixed this yesterday

**Comment by grousso** [comment]
I update with
sudo flat pack update 
There was an update for Recipes but the issue remains.

**Comment by grousso** [comment]
ok, now it doesn’t crash but it doesn’t open "My Recipies" window too. Actually is like clicking to a dead button.

** Message: Could not talk to Account portal: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files
** Message: Failed to get account information: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files
** Message: Could not talk to Account portal: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files
** Message: Failed to get account information: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files
